### ISSUE TITLE
No active deployment shown when the first app deploy is in progress (step: build-image)

### ISSUE THREAD

**Issue by ramraj-patel** [zigmoi/ketchup-core#7]
![Screenshot from 2021-02-01 00-42-50](https://user-images.githubusercontent.com/10565613/106395114-7e928b00-6426-11eb-871a-86f0830a14c0.png)

**Comment by aldersun-elliot** [comment]
Is the application level monitoring enabled ? we need to update a ketchup base url in properties file, this url should be accessible from within the cluster.

**Comment by aldersun-elliot** [comment]
Setting the `ketchup.base-url` in application.properties in install step such that ketchup core app is accessible from inside the cluster is needed so that ketchup gets updates from cluster for tekton pipeline events.
Setting this property should resolve the issue.
